- name: access variable from play level
  hosts: all
  connection: local
  vars:
    abc: "clark.in"
  tasks:
    - name: access variable
      ansible.builtin.debug:
        msg: abc = {{ abc }}

- name: at task level
  hosts: all
  connection: local
  tasks:
    - name: access
      ansible.builtin.debug:
        msg: abc = {{ abc }}
      vars:
        abc: task.com

- name: file level
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: access
      ansible.builtin.debug:
        msg: abc = {{ abc }}